version: '3'

services:
  allure:
    image: "frankescobar/allure-docker-service"
    user: 1000:1000
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 30
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 10
    ports:
      - "5050:5050"
    volumes:
      - ./build/allure-results:/app/allure-results
      - ./build/reports/allure-report:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"